"""
Django settings for auth_service project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
import logging
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(Path(__file__).resolve().parent, "templates")
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.debug(os.path.join(BASE_DIR, ".env"))

if os.path.exists(os.path.join(BASE_DIR, ".env")):
    # reading .env file
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = [
    '0.0.0.0',
    'auth-dev',
    'auth',
    "localhost",
    '127.0.0.1',
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_HOST_PORT")
EMAIL_USE_SSL = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")


# Application definition

INSTALLED_APPS = [
    "health_check",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    # "oauth2_provider",
    "users",
    'rest_framework_simplejwt.token_blacklist',
    # "audit",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}


# def get_key_from_file(filepath):
#     """Считывает ключ из файла, если он существует."""
#     if os.path.isfile(filepath):
#         with open(filepath, "r") as f:
#             return f.read()
#     return None


# PRIVATE_KEY_PATH = os.path.join(BASE_DIR, "certs", "jwt_private.pem")
# PUBLIC_KEY_PATH = os.path.join(BASE_DIR, "certs", "jwt_public.pem")

# SIGNING_KEY = get_key_from_file(PRIVATE_KEY_PATH
# VERIFYING_KEY = get_key_from_file(PUBLIC_KEY_PATH)

SIGNING_KEY = env("SIGNING_KEY")
VERIFYING_KEY = env("VERIFYING_KEY")


# OAUTH2_PROVIDER = {
#     "PKCE_REQUIRED": True,
#     "OIDC_ENABLED": True,
#     "OIDC_RSA_PRIVATE_KEY": SIGNING_KEY,
#     # "OIDC_RSA_PUBLIC_KEY": PUBLIC_KEY_PATH,
#     "DEFAULT_ID_TOKEN_SIGNING_ALG": "RS256",
#     "ALLOWED_REDIRECT_URI_SCHEMES": ["http", "https", "com.wearai.app"],
#     "SCOPES": {
#         "read": "Read scope",
#         "write": "Write scope",
#         "email": "Access to your email",
#         "openid": "OpenID Connect scope",
#         "profile": "User profile information",
#     },
# }

ACCESS_TOKEN_LIFETIME_STR = env("ACCESS_TOKEN_LIFETIME")
REFRESH_TOKEN_LIFETIME_STR = env("REFRESH_TOKEN_LIFETIME")

def to_int(value, default):
    try:
        return int(value) if value is not None else default
    except (ValueError, TypeError):
        return default

ACCESS_TOKEN_LIFETIME = to_int(ACCESS_TOKEN_LIFETIME_STR, 60)
REFRESH_TOKEN_LIFETIME = to_int(REFRESH_TOKEN_LIFETIME_STR, 365)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_TOKEN_LIFETIME),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_TOKEN_LIFETIME),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    "ALGORITHM": "RS256",
    "SIGNING_KEY": SIGNING_KEY,
    "VERIFYING_KEY": VERIFYING_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_USER_MODEL = "users.ABSUser"

OIDC_RP_INITIATED_LOGOUT_ENABLED = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "oauth2_provider": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "auth_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "auth_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}

REDIS_URL = env("REDIS_URL")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        },
    },
    "otp_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
    "reg_token_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

PEPPERED_PASSWORDS_SECRET_KEY = env("PEPPERED_PASSWORDS_SECRET_KEY")

PASSWORD_HASHERS = [
    "auth_service.custom_hashers.PepperedBCryptSHA256PasswordHasher",
    # "django_peppered_passwords.hashers.PepperedBCryptPasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
    ("fr", "Français"),
    ("de", "Deutsch"),
    ("es", "Español"),
    ("ja", "日本語"),
]

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

OTP_TIMEOUT_ENV = env("OTP_TIMEOUT")
REG_TOKEN_TIMEOUT_ENV = env("REG_TOKEN_TIMEOUT")

if not (
    (OTP_TIMEOUT_ENV and isinstance(OTP_TIMEOUT_ENV, int))
    and (REG_TOKEN_TIMEOUT_ENV and isinstance(REG_TOKEN_TIMEOUT_ENV, int))
):
    OTP_TIMEOUT_ENV = 5
    REG_TOKEN_TIMEOUT_ENV = 10

OTP_TIMEOUT: int = int(timedelta(minutes=OTP_TIMEOUT_ENV).total_seconds())
REG_TOKEN_TIMEOUT: int = int(timedelta(minutes=REG_TOKEN_TIMEOUT_ENV).total_seconds())